### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by auto200** [Bartek532/ecommerce-sofa#1]
### Problem:
Can't go back to previous website that links to the shop

### Enviroment:
Do not be logged in to the shop

### Steps to reproduce:
1. Open this link in the same tab [https://ecommerce-sofa.vercel.app](https://ecommerce-sofa.vercel.app)
2. Try to navigate back to this issue

### Expected behaviour
User backs to previous website

### Actual behaviour
User is stuck on shop website

https://github.com/Bartek532/ecommerce-sofa/blob/5b19bdca243ed0c0b55d0ae2103bfade7453eb8b/components/organisms/AuthChecker.tsx#L21-L26

**Comment by Bartek532** [comment]
Thanks for your report 😍 I have to fix it, but remember: you can always create a PR and help me 😁

**Comment by Bartek532** [comment]
hmm, strange, everything seems to be working for me 😁 could you please provide the name of the browser/device or preferably the video where you can see the error? @auto200

**Comment by auto200** [comment]
I managed to navigate back once on chrome, used guest mode to ensure no extensions are interfering. I alternated between clicking on back button and clicking back button on mouse.

https://user-images.githubusercontent.com/49625375/121339354-b05cb680-c91e-11eb-8752-20248f638810.mp4

**Comment by Bartek532** [comment]
Thanks! I pushed some changes and I think everything should be working now, check it out! 😁

**Comment by auto200** [comment]
@Bartek532 Yep, everything seems to be working. Great job 😃👍
